return {
  "jay-babu/mason-null-ls.nvim",
  event = { "BufReadPre", "BufNewFile" },
  dependencies = {
    "williamboman/mason.nvim",
    "nvimtools/none-ls.nvim",
  },
  config = function()
    require("mason-null-ls").setup({
      automatic_installation = true,
      ensure_installed = {
        "stylua",
        "jq",
        "fixjson",
        "lua-language-server",
        "texlab",
        "latexindent",
        "actionlint",
        "bibtex-tidy ",
        "commitlint",
        "debugpy",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "gitleaks",
        -- 'isort',
        -- 'prettier',
        -- "pyflakes",
        -- 'taplo',
        -- 'yaml-language-server',
        -- "jedi-language-server",
        "yamlfix",
        "cmakelang",
        "cmake-language-server",
        "bash-language-server",
        "shellcheck",
        "beautysh",
        "markdownlint",
        -- 'ansible-lint',
        -- 'ansible-language-server',
      },
    })
  end,
}
